name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'  # trigger saat push tag version

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # atau versi yang kamu pakai
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable  # penting untuk Yarn modern
      - run: yarn install --immutable
      - run: yarn build  # kalau ada build step
      - run: npm publish --access public  # atau yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
